// Generated by view binder compiler. Do not edit!
package com.example.option1_inventoryapp_rayyanabdulmunib.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.option1_inventoryapp_rayyanabdulmunib.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentRegisterBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button login;

  @NonNull
  public final Button register;

  @NonNull
  public final TextView registerTitle;

  @NonNull
  public final EditText setPassword;

  @NonNull
  public final EditText setUsername;

  private FragmentRegisterBinding(@NonNull ConstraintLayout rootView, @NonNull Button login,
      @NonNull Button register, @NonNull TextView registerTitle, @NonNull EditText setPassword,
      @NonNull EditText setUsername) {
    this.rootView = rootView;
    this.login = login;
    this.register = register;
    this.registerTitle = registerTitle;
    this.setPassword = setPassword;
    this.setUsername = setUsername;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.login;
      Button login = ViewBindings.findChildViewById(rootView, id);
      if (login == null) {
        break missingId;
      }

      id = R.id.register;
      Button register = ViewBindings.findChildViewById(rootView, id);
      if (register == null) {
        break missingId;
      }

      id = R.id.registerTitle;
      TextView registerTitle = ViewBindings.findChildViewById(rootView, id);
      if (registerTitle == null) {
        break missingId;
      }

      id = R.id.setPassword;
      EditText setPassword = ViewBindings.findChildViewById(rootView, id);
      if (setPassword == null) {
        break missingId;
      }

      id = R.id.setUsername;
      EditText setUsername = ViewBindings.findChildViewById(rootView, id);
      if (setUsername == null) {
        break missingId;
      }

      return new FragmentRegisterBinding((ConstraintLayout) rootView, login, register,
          registerTitle, setPassword, setUsername);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
